### PR TITLE
Fix two bugs found in the CHashMap

### PR DESCRIPTION
**Pull request by bricehulse**
These are fixes for two issues I ran into using CHashMap:

1. If you use alter() to change the value for a key that already exists in the map, the len field gets incremented, even though it should stay the same.

2. If you do a bunch of alternating insertions and removals, you can end up with a situation where every single bucket is either used or "free" (i.e. none of them are "empty"). If you try to insert another entry when this is a case, it goes into an infinite loop when it looks for a bucket to place the new entry in, because it expects to find an "empty" bucket at the end of the cluster, but there are no empty buckets.

### CODE REVIEW

**Comment by ticki** [comment]
Sorry for being late. These are some interesting finds indeed!

**Comment by daiheitan** [comment]
Would you please release a new version of Chashmap? @ticki

**Comment by ticki** [comment]
I'll do.

**Comment by ticki** [comment]
It's up now, @daiheitan

**Comment by daiheitan** [comment]
thanks

**Comment by daiheitan** [comment]
@ticki I'm stilling getting CPU 100% usage even after this patch. There're two other infinite loop in `chashmap`, do you think may any of them still causing the problem?

**Comment by daiheitan** [comment]
@ticki ping

**Pull request merged**
