### PR TITLE
SeaHash: fix pop() and add larger output

### PR DESCRIPTION
**Pull request by dhardy**
@ticki, if you are able to review?

The larger output functions are wanted for a slightly obscure use, seeding PRNGs:
https://github.com/dhardy/rand/issues/18#issuecomment-345190063

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
ping?

**Comment by bjorn3** [comment]
https://ticki.github.io/blog/why_im_leaving_open_source/

**Comment by dhardy** [comment]
Thanks for passing on the message.

For my part, I don't think the additional finalisation functions will be useful (this was basically a hack and isn't really suitable for almost anything you'd want a 128- or 256-bit hash for).

The other bits may still be worth merging if someone is still maintaining this.

**Comment by jackpot51** [comment]
Please take a look here: https://gitlab.redox-os.org/redox-os/seahash

Perhaps you can rebase your change on that repository

**Comment by dhardy** [comment]
Looks like someone else already landed my fixes in that repo. The wider output functions are probably not useful.

**Pull request closed without merging**
